// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// (opencode comment) `env` was used below without being imported -> added it to the import
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: env("DATABASE_URL")
  },
});
